server:
  port: 8080
spring:
#  task:
#    scheduling:
#      pool:
#        size: 10  这意味着你配置了Spring的任务调度器（TaskScheduler）线程池大小为1。
#  请注意，这并不直接影响到使用@Async注解的方法的执行方式，
#  因为@Async方法默认使用的不是任务调度器的线程池，而是异步任务执行器（比如SimpleAsyncTaskExecutor或其他自定义的TaskExecutor）。
  application:
    name: schedule
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/my_schedule?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 12345678
  redis:
    host: 192.168.174.129
    port: 6379
    password: 123456
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #???????

mybatis-plus:
  configuration:
    #???????????????????????????????????????
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /src/main/resources/uploads/

zodiac:
  key: 523bfe2b0d574e03e7698bd43aaa6dce
constellation:
  key: ce4c8f8aae082acdabfbf733b55bfae6
weixin:
  jscode2sessionUrl: https://api.weixin.qq.com/sns/jscode2session
  appid: wxae2ca77ab20990ea  #修改自己的微信小程序 appId
  secret: d3396d7c27d55d70a19790d2cc4b85ac   #修改自己的微信小程序 appSecret